add skip test flag
wishabi/github-actions pull request #170
Opened 2024-09-27 15:48 UTC by chriskarlin

2024-09-27 15:48 UTC, chriskarlin commented on go/build-and-test/action.yml
> +  SKIP_TESTS:
nit
```suggestion
  SKIP_TEST:
```

2024-10-22 13:27 UTC, dcbickfo requested changes
I think you managed this in a different way, but my vote would be to have a separate build action (like what we had when I was playing with caching) and let the calling workflow skip running the tests rather than skipping part of this action.

2025-03-28 17:13 UTC, chriskarlin commented
@dcbickfo good idea, I went ahead with this approach

2025-03-28 18:19 UTC, dcbickfo commented on go/build/action.yml
> +runs:
Can we just call this from `build-and-test`? It seems like it should be possible. The slack alert won't fire if `build-and-test` doesn't pass down the slack channel ID, so we won't get duplicate messages.

2025-03-28 18:29 UTC, chriskarlin commented on go/build/action.yml
> +runs:
Done testing on a new branch in dist-api now

2025-03-28 18:31 UTC, chriskarlin commented on go/build/action.yml
> +runs:
https://github.com/wishabi/distribution-api/pull/648

2025-03-28 20:06 UTC, dcbickfo commented on go/build/action.yml
> +    - name: Configure Go environment
Why does this one need configure and the old build and test action didnt?

2025-03-28 20:18 UTC, dcbickfo commented
> This could really be scraped if we call `wishabi/github-actions/go/configure@v0` + `wishabi/github-actions/go/deps@v0` + `wishabi/github-actions/go/test@v0` instead of `wishabi/github-actions/go/build-and-test@v0` from distribution-api

I feel like that might be taking us full circle. I think we were doing that at some point 😂

2025-03-28 20:41 UTC, chriskarlin commented on go/build/action.yml
> +    - name: Configure Go environment
But it did :P 
![image](https://github.com/user-attachments/assets/e661daf7-a050-4b97-af80-43ef42e170f9)

2025-03-28 21:08 UTC, dcbickfo commented on go/build/action.yml
> +    - name: Configure Go environment
I read the diff wrong

2025-03-28 21:08 UTC, dcbickfo approved these changes

2025-03-28 21:17 UTC, merged